---

- hosts: all
  become: true
  tasks:
    - name: Install hello world
      tags: docker

      community.docker.docker_image_pull:
        name: testcontainers/helloworld

    - name: Update sonnar containers
      tags: docker,sonar
      community.docker.docker_compose_v2_pull:
        project_src: /mnt/raid/sonarr/
      register: sonnar_changed

    - name: Restart sonarr compose
      community.docker.docker_compose_v2:
        project_src: /mnt/raid/sonarr/
        state: present
        recreate: auto
      when: sonnar_changed.changed
      

    - name: Update immich containers
      tags: docker,immich
      community.docker.docker_compose_v2_pull:
        project_src: /mnt/raid/immich-app/
      register: immich_changed

    - name: rsync immich data
      tags: immich,docker
      synchronize:
        src: /mnt/raid/immich-app/
        dest: /media/yanec/Expansion/immich-app.backup/
        archive: true
        group: false
        owner: false
        mode: push
        rsync_opts:
          - "--exclude='**/thumbs/'"
          - "--exclude='**/encoded-video/'"
          - "--delete"
      delegate_to: "{{ inventory_hostname }}"
      when: immich_changed.changed

    - name: Restart immich compose
      community.docker.docker_compose_v2:
        project_src: /mnt/raid/immich-app/
        state: present
        recreate: auto
      when: immich_changed.changed

    - name: Update jacket containers
      tags: docker,jacket
      community.docker.docker_compose_v2_pull:
        project_src: /mnt/raid/jackett/
      register: jacket_changed

    - name: Restart jacket compose

      community.docker.docker_compose_v2:
        project_src: /mnt/raid/jackett/
        state: present
        recreate: auto
      when: jacket_changed.changed

    - name: Update jellyfin containers
      tags: docker,jellyfin
      community.docker.docker_compose_v2_pull:
        project_src: /mnt/raid/jillyfin/
      register: jellyfin_changed

    - name: Restart jellyfin compose
      community.docker.docker_compose_v2:
        project_src: /mnt/raid/jillyfin/
        state: present
        recreate: auto
      when: jellyfin_changed.changed

    #homeassistant/
    - name: Update homeassistant containers
      tags: docker,homeassistant
      community.docker.docker_compose_v2_pull:
        project_src: /mnt/raid/homeassistant/
      register: homeassistant_changed

    - name: Restart homeassistant compose
      community.docker.docker_compose_v2:
        project_src: /mnt/raid/homeassistant/
        state: present
        recreate: auto
      when: homeassistant_changed.changed
      
      #torrent
    - name: Update torrent containers
      tags: docker,torrent
      community.docker.docker_compose_v2_pull:
        project_src: /mnt/raid/torrent/
      register: torrent_changed

    - name: Restart torrent compose
      community.docker.docker_compose_v2:
        project_src: /mnt/raid/torrent/
        state: present
        recreate: auto
      when: torrent_changed.changed  
#nginx-container
    - name: Update nginx-container containers
      tags: docker,nginx
      community.docker.docker_compose_v2_pull:
        project_src: /mnt/raid/nginx-container/
      register: nginx_changed

    - name: Restart nginx-container compose
      community.docker.docker_compose_v2:
        project_src: /mnt/raid/nginx-container/
        state: present
        recreate: auto
      when: nginx_changed.changed      
#monitoring(prometheus, grafana, cadvisor, node-exporter)
    - name: Update monitoring containers
      tags: docker,monitoring,prometheus,grafana,cadvisor,node-exporter
      community.docker.docker_compose_v2_pull:
        project_src: /mnt/raid/monitoring/
      register: monitoring_changed

    - name: Restart monitoring compose
      community.docker.docker_compose_v2:
        project_src: /mnt/raid/monitoring/
        state: present
        recreate: auto
      when: monitoring_changed.changed

#nextcloud
    - name: Pull latest nextcloud image
      tags: build
      docker_image:
        name: nextcloud:latest
        source: pull
      register: nextcloud_pulled

    - name: Build Docker image manually
      become: yes
      tags: build
      command: docker build -t nextcloud-with-smbclient .
      args:
        chdir: /mnt/raid/nextcloud
      register: build_output
      when: nextcloud_pulled.changed

    - name: Restart nextcloud compose
      tags: build
      community.docker.docker_compose_v2:
        project_src: /mnt/raid/nextcloud/
        state: present
        recreate: auto
      when: nextcloud_pulled.changed    
    - name: rsync raid data to external drive
      tags: backup,docker
      synchronize:
        src: /mnt/raid/
        dest: /media/yanec/Expansion/cloud
        archive: true
        group: false
        owner: false
        copy_links: true
        mode: push
        rsync_opts:
          - "--exclude='immich-app'" 
          - "--exclude='storage'"
          - "--exclude='**/files_trashbin/'"
          - "--exclude='lost+found'"
          - "--exclude='**/app-discover-cache/'"
          - "--exclude='**/*ipc-socket*'"
          - "--exclude='**/*logs*'"
          - "--delete"
      delegate_to: "{{ inventory_hostname }}"
      when: nextcloud_pulled.changed        

    # - name: build nextcloud container
    #   tags: build
    #   community.docker.docker_image:
    #     name: nextcloud-with-smbclient-new
    #     build:
    #       path: /mnt/raid/nextcloud
    #       dockerfile: Dockerfile
    #     source: build

    # - name: Update nextcloud containers
    #   tags: docker,nextcloud
    #   community.docker.docker_compose_v2_pull:
    #     project_src: /mnt/raid/nextcloud/
    #   register: nextcloud_changed



    # - name: Restart nextcloud compose
    #   community.docker.docker_compose_v2:
    #     project_src: /mnt/raid/nextcloud/
    #     state: present
    #     recreate: auto
    #   when: nextcloud_changed.changed
  #sudo rsync -avh --progress --no-owner --no-group --delete --exclude='immich-app' --exclude='storage' --exclude="**/files_trashbin/" --exclude='lost+found' /mnt/raid/ /media/yanec/Expansion/cloud
    # - name: Update {{ service_name }} containers
    #   tags: docker,{{ service_name }}
    #   community.docker.docker_compose_v2_pull:
    #     project_src: /mnt/raid/{{ service_name }}/
    #   register: "{{ service_name }}_changed"

    # - name: Update {{ service_name }}
    #   community.docker.docker_compose_v2:
    #     project_src: /mnt/raid/{{ service_name }}
    #     state: present
    #     recreate: auto
    #   when: "{{ service_name }}_changed.changed"


# sudo rsync -avh --progress --no-owner --no-group --delete --exclude='**/thumbs/' --exclude='**/encoded-video/' /mnt/raid/immich-app/ /media/yanec/Expansion/immich-app.backup/