version: "3.8"

networks:
  nginx-network:
    external: true

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - /etc/letsencrypt/live/interamazing.com:/etc/letsencrypt/live/interamazing.com:ro
      - /etc/letsencrypt/archive/interamazing.com:/etc/letsencrypt/archive/interamazing.com:ro
    networks:
      - nginx-network
    restart: unless-stopped
